### ISSUE TITLE
EmbyClient Not Working

### ISSUE THREAD

**Issue by kingy444** [nwithan8/embyclient_python#1]
Hey @nwithan8

Understand you are auto building so potentially nothing for you just yet.

I couldnt get your pypi published to work, so pulled the core sdk and that also failed. I have raised with the emby team below, but an outcome to this could mean you need to adjust some of your build too.

They are likely to rename ``embyclient-python`` as the ``-`` is currently breaking the build process. Looks like you are currently looking the module up via this in the ``check_and_build_latest_release.sh``

Here is the forum post i raised: https://emby.media/community/index.php?/topic/129543-python-api-client/

**Comment by nwithan8** [comment]
Thanks for letting me know, I'll monitor the situation.

**Comment by kingy444** [comment]
@nwithan8 any chance you could publish the beta repo as a pre/beta release ?
The project I'm working on needs to pull the package at build time so this would be helpful until the emby team have promoted to production.

https://github.com/MediaBrowser/Emby.SDK/tree/beta/SampleCode/RestApi/Clients/Python/emby_client

**Comment by nwithan8** [comment]
Sorry it took me so long. I've updated the process to also find and build stuff on the "beta" branch as well. Unfortunately, it removes "-Beta" from the version number published on PyPi, probably because it's invalid version syntax on the platform: https://pypi.org/project/embyclient/4.9.0.29/
